# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
-
  id: sidecar-executor
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64

archives:
- 
  replacements:
    linux: Linux
    amd64: x86_64
  builds:
    - sidecar-executor
  files:
    - README.md
    - LICENSE
    - executor.sh

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"


changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
